spring:
  application:
    name: jennifer.cubillas
  data:
    mongodb:
      uri: mongodb+srv://alecubillas31:Cubillas31@cluster0.q8n7w4f.mongodb.net/ia_db?retryWrites=true&w=majority&appName=Cluster0
  autoconfigure:
    exclude:
      - de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration

logging:
  level:
    org.mongodb.driver: ERROR
    org.mongodb.driver.cluster: ERROR
    org.mongodb.driver.connection: ERROR
server:
  port: 8080

rapidapi:
  key: c7670db228msh4c0aee5e9a2ce22p14bf95jsndfd065182e43
  deep-translate:
    url: https://deep-translate1.p.rapidapi.com/language/translate/v2
    host: deep-translate1.p.rapidapi.com
  openai21:
    url: https://chatgpt-api8.p.rapidapi.com/
    host: chatgpt-api8.p.rapidapi.com
