apiVersion: v1
kind: Secret
metadata:
  name: jennifer-cubillas-08-secret
  namespace: jennifer-cubillas-08
type: Opaque
stringData:
  # MongoDB Atlas Connection String
  MONGODB_URI: "mongodb+srv://alecubillas31:Cubillas31@cluster0.q8n7w4f.mongodb.net/ia_db?retryWrites=true&w=majority&appName=Cluster0"
  MONGODB_DATABASE: "ia_db"
  
  # RapidAPI Key
  RAPIDAPI_KEY: "c7670db228msh4c0aee5e9a2ce22p14bf95jsndfd065182e43"
  
  # Deep Translate API
  DEEP_TRANSLATE_URL: "https://deep-translate1.p.rapidapi.com/language/translate/v2"
  DEEP_TRANSLATE_HOST: "deep-translate1.p.rapidapi.com"
  
  # ChatGPT API8
  OPENAI21_URL: "https://chatgpt-api8.p.rapidapi.com/"
  OPENAI21_HOST: "chatgpt-api8.p.rapidapi.com"
